controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    fake_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
      state_publish_rate: 25
      action_monitor_rate: 10
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        joint1: {trajectory: 0.2, goal: 0.1}
        joint2: {trajectory: 0.2, goal: 0.1}
        joint3: {trajectory: 0.2, goal: 0.1}
        joint4: {trajectory: 0.2, goal: 0.1}
