move_group:
  ros__parameters:
    planning_plugin: ompl_interface/OMPLPlanner
    default_planning_pipeline: move_group
    planning_pipelines: [move_group]
    robot_description_kinematics:
      manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_timeout: 1.0
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_attempts: 10
    robot_description: |
      <?xml version="1.0" ?>
      <!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
       DoBot Magician Lite with suction cup and camera mounts. Modified for ROS2 MoveIt integration. -->
      <robot name="magician_description">
        <link name="base_footprint"/>
        <link name="base_link">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.1" radius="0.05"/>
            </geometry>
            <material name="gray">
              <color rgba="0.5 0.5 0.5 1"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.1" radius="0.05"/>
            </geometry>
          </collision>
        </link>
        <link name="shoulder">
          <visual>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.1" radius="0.03"/>
            </geometry>
            <material name="blue">
              <color rgba="0 0 1 1"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.1" radius="0.03"/>
            </geometry>
          </collision>
        </link>
        <link name="elbow">
          <visual>
            <origin xyz="0 0 0.08" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.16" radius="0.025"/>
            </geometry>
            <material name="green">
              <color rgba="0 1 0 1"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0.08" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.16" radius="0.025"/>
            </geometry>
          </collision>
        </link>
        <link name="wrist">
          <visual>
            <origin xyz="0 0 0.08" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.16" radius="0.025"/>
            </geometry>
            <material name="red">
              <color rgba="1 0 0 1"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0.08" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.16" radius="0.025"/>
            </geometry>
          </collision>
        </link>
        <link name="wrist_pitch">
          <visual>
            <origin xyz="0 0 0.02" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.04" radius="0.015"/>
            </geometry>
            <material name="purple">
              <color rgba="1 0 1 1"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0.02" rpy="0 0 0"/>
            <geometry>
              <cylinder length="0.04" radius="0.015"/>
            </geometry>
          </collision>
        </link>
        <joint name="base_to_base_link" type="fixed">
          <parent link="base_footprint"/>
          <child link="base_link"/>
          <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>
        <joint name="joint1" type="revolute">
          <parent link="base_link"/>
          <child link="shoulder"/>
          <origin xyz="0 0 0.1" rpy="0 0 0"/>
          <axis xyz="0 0 1"/>
          <limit lower="-3.14159" upper="3.14159" effort="100" velocity="1.0"/>
        </joint>
        <joint name="joint2" type="revolute">
          <parent link="shoulder"/>
          <child link="elbow"/>
          <origin xyz="0 0 0.1" rpy="0 0 0"/>
          <axis xyz="0 1 0"/>
          <limit lower="-1.5708" upper="1.5708" effort="100" velocity="1.0"/>
        </joint>
        <joint name="joint3" type="revolute">
          <parent link="elbow"/>
          <child link="wrist"/>
          <origin xyz="0 0 0.16" rpy="0 0 0"/>
          <axis xyz="0 1 0"/>
          <limit lower="-1.5708" upper="1.5708" effort="100" velocity="1.0"/>
        </joint>
        <joint name="joint4" type="revolute">
          <parent link="wrist"/>
          <child link="wrist_pitch"/>
          <origin xyz="0 0 0.16" rpy="0 0 0"/>
          <axis xyz="0 1 0"/>
          <limit lower="-1.5708" upper="1.5708" effort="100" velocity="1.0"/>
        </joint>
      </robot>
    robot_description_semantic: |
      <?xml version="1.0" ?>
      <robot name="magician_description">
        <group name="magician_arm">
          <chain base_link="base_link" tip_link="wrist_pitch"/>
          <joint name="joint1"/>
          <joint name="joint2"/>
          <joint name="joint3"/>
          <joint name="joint4"/>
        </group>
        <group_state name="ready" group="magician_arm">
          <joint name="joint1" value="0"/>
          <joint name="joint2" value="0"/>
          <joint name="joint3" value="0"/>
          <joint name="joint4" value="0"/>
        </group_state>
        <virtual_joint name="fixed_base" type="fixed" parent_frame="world" child_link="base_footprint" />
        <disable_collisions link1="base_link" link2="shoulder" reason="Adjacent" />
        <disable_collisions link1="shoulder" link2="elbow" reason="Adjacent" />
        <disable_collisions link1="elbow" link2="wrist" reason="Adjacent" />
        <disable_collisions link1="wrist" link2="wrist_pitch" reason="Adjacent" />
      </robot>
